# -*- coding: utf-8 -*-
"""12 Streamlit App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZKzCEWOIvMHjksa56o13c-vln4qR3Jq
"""

import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/Projects/Experiment/12 Streamlit App Dashboard/customer_profile.csv')
data.head()

data.info()

data.describe(include='all')

data['DATE_OPEN_CIF_2'] = pd.to_datetime(data['DATE_OPEN_CIF_2'],dayfirst = True,errors = 'coerce')
data.info()

data.DATE_OPEN_CIF_2

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Dashboard Sederhana 🚀")
# 
# st.subheader("Preview Data")
# st.dataframe(data)
# 
# # Tambah chart sederhana (ganti sesuai datamu)
# st.subheader("Visualisasi Contoh")
# st.line_chart(data['CABANG'])

