# -*- coding: utf-8 -*-
"""12 Streamlit App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZKzCEWOIvMHjksa56o13c-vln4qR3Jq
"""

import pandas as pd

data = pd.read_csv('customer_profile.csv')
data.head()

data.info()

data.describe(include='all')

data['DATE_OPEN_CIF_2'] = pd.to_datetime(data['DATE_OPEN_CIF_2'],dayfirst = True,errors = 'coerce')
data.info()

data.DATE_OPEN_CIF_2.head()


# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
import streamlit as st
# 
st.title("Branch Dashboard")
# 
# st.subheader("Preview Data")
# st.dataframe(data)
# 
# # Tambah chart sederhana (ganti sesuai datamu)
st.subheader("Customer Profile")
# st.line_chart(data['CABANG'])

# Dropdown untuk CABANG
selected_cabang = st.selectbox(
    'Pilih Cabang:',
    options=sorted(data['CABANG'].dropna().unique())
)

# Dropdown untuk PERIODE
selected_periode = st.selectbox(
    'Pilih Periode:',
    options=sorted(data['PERIODE'].dropna().unique())
)

# Filter data sesuai pilihan
filtered_data = data[
    (data['CABANG'] == selected_cabang) & (data['PERIODE'] == selected_periode)
]

# Hitung statistik
nunique_customer = filtered_data['CUSTOMER_NO'].nunique()
nunique_account = filtered_data['ACCOUNT_NUMBER'].nunique()
new_cif_count = (filtered_data['NEW_CIF'] == 'Y').sum()

# Tampilkan ke Streamlit
st.metric("Jumlah Customer", nunique_customer)
st.metric("Jumlah Account", nunique_account)
st.metric("Jumlah NEW_CIF = Y", new_cif_count)
