# -*- coding: utf-8 -*-
"""12 Streamlit App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZKzCEWOIvMHjksa56o13c-vln4qR3Jq
"""

import pandas as pd

data = pd.read_csv('customer_profile.csv')
data.head()

data.info()

data.describe(include='all')

data['DATE_OPEN_CIF_2'] = pd.to_datetime(data['DATE_OPEN_CIF_2'],dayfirst = True,errors = 'coerce')
data.info()

data.DATE_OPEN_CIF_2

# Dropdown untuk CABANG
selected_cabang = st.selectbox(
    'Pilih Cabang:',
    options=sorted(data['CABANG'].dropna().unique())
)

# Dropdown untuk PERIODE
selected_periode = st.selectbox(
    'Pilih Periode:',
    options=sorted(data['PERIODE'].dropna().unique())
)

# Tampilkan hasil pilihan
st.write(f"Cabang yang dipilih: **{selected_cabang}**")
st.write(f"Periode yang dipilih: **{selected_periode}**")

# Filter data sesuai pilihan
filtered_data = data[(data['CABANG'] == selected_cabang) & (data['PERIODE'] == selected_periode)]

# Tampilkan data hasil filter
st.dataframe(filtered_data)

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Dashboard Sederhana 🚀")
# 
# st.subheader("Preview Data")
# st.dataframe(data)
# 
# # Tambah chart sederhana (ganti sesuai datamu)
# st.subheader("Visualisasi Contoh")
# st.line_chart(data['CABANG'])

